name: repositories
on:
  pull_request:
    paths:
      - 'files/overlays/repositories.xml'

jobs:
  validate-content:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install pip dependencies
      run: pip install lxml

    - name: Check repositories.xml
      run: |
        BASE_REF=$(git merge-base --fork-point origin/${{ github.base_ref }})
        python .github/repositories-checker.py <(git show ${BASE_REF}:files/overlays/repositories.xml) files/overlays/repositories.xml

  validate-schema:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download repositories.xml schema
      run: wget https://gitweb.gentoo.org/data/xml-schema.git/plain/repositories.xsd

    - name: Prepare xmllint annotator
      uses: korelstar/xmllint-problem-matcher@v1

    - name: Lint repositories.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./files/overlays/repositories.xml
        xml-schema-file: ./repositories.xsd
