name: trying
on:
  pull_request:
    paths:
      - 'files/overlays/repositories.xml'

jobs:
  repositories:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check Emails against bugzilla
      run: |
        BASE_REF=$(git merge-base --fork-point origin/${{ github.base_ref }})
        python ./.github/email-checker.py files/overlays/repositories.xml <(git show ${BASE_REF}:files/overlays/repositories.xml)
