name: repositories
on:
  push

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download schema
      run: wget https://gitweb.gentoo.org/data/xml-schema.git/plain/repositories.xsd

    - name: Prepare xmllint annotator
      uses: korelstar/xmllint-problem-matcher@v1

    - name: Lint repositories.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./files/overlays/repositories.xml
        xml-schema-file: ./repositories.xsd
