name: trying
on: [push, pull_request]

jobs:
  job:
    name: Basic (${{ matrix.triplet }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - triplet: x64-windows
            vcpkgCommitId: '030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1'
            vcpkgPackages: 'taglib libpng ffmpeg[ffmpeg,iconv,vorbis,openssl,mp3lame,swresample,swscale,bzip2,zlib] qt5[core,quickcontrols2,extras]'

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          
      - name: Export outputs of run-vcpkg task
        run: |
          ${{ runner.workspace }}/b/vcpkg/vcpkg.exe export --triplet=${{ matrix.triplet }} --7zip ${{ matrix.vcpkgPackages }}
          dir ${{ runner.workspace }}/b/vcpkg/vcpkg-export-*
          
      - name: Upload Export
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: vcpkg-export
          path: |
            ${{ runner.workspace }}/b/vcpkg/vcpkg-export-*
            
            
      - name: Run CMake+Ninja with triplet (cmd)
        uses: lukka/run-cmake@main
        id: runcmake_cmd
        with:
          cmakeGenerator: 'Ninja'
          cmakeBuildType: 'Release'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          #cmakeAppendedArgs: -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON
          vcpkgTriplet: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
      - name: Install
        run: |
          cd '${{ runner.workspace }}/b/ninja/'
          cmake --install . --prefix out
          cpack -G WIX .
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: Build Dir
          path: |
            ${{ runner.workspace }}/b/ninja/
            ${{ runner.workspace }}/b/vcpkg/installed/